blank_issues_enabled: true
contact_links:
  - name: Homey Community Forum
    url: https://community.homey.app/
    about: For general questions and community support
  - name: Documentation
    url: https://github.com/ThomasHoussin/com.thomashoussin.fronius/blob/main/README.md
    about: Check the README for basic usage information
